/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  534351: {
    Database: {
      address: "0x1CD8616DF70878bC5a829B7F571361f1d27A3A30",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_wallet",
              type: "address",
            },
          ],
          name: "addAdmin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "dadAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
          ],
          name: "addChildDad",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "momAddress",
              type: "address",
            },
            {
              internalType: "address",
              name: "childAddress",
              type: "address",
            },
          ],
          name: "addChildMom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_wallet",
              type: "address",
            },
            {
              components: [
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "cpf",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "mae",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "pai",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "dataNascimento",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "naturalidade",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "nacionalidade",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "sexo",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "matricula",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "nomeMae",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "nomePai",
                  type: "string",
                },
              ],
              internalType: "struct Database.Person",
              name: "person",
              type: "tuple",
            },
          ],
          name: "addPerson",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "admins",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "childDadChain",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "childMomChain",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "digitalChain",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "person",
              type: "address",
            },
            {
              internalType: "string",
              name: "_newName",
              type: "string",
            },
          ],
          name: "editName",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "momAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "_newName",
              type: "string",
            },
          ],
          name: "editNameMom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "dadAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "_newName",
              type: "string",
            },
          ],
          name: "editNamedad",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "idChain",
          outputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "cpf",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "mae",
              type: "address",
            },
            {
              internalType: "address",
              name: "pai",
              type: "address",
            },
            {
              internalType: "string",
              name: "dataNascimento",
              type: "string",
            },
            {
              internalType: "string",
              name: "naturalidade",
              type: "string",
            },
            {
              internalType: "string",
              name: "nacionalidade",
              type: "string",
            },
            {
              internalType: "string",
              name: "sexo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "matricula",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "nomeMae",
              type: "string",
            },
            {
              internalType: "string",
              name: "nomePai",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "digital",
                  type: "uint256",
                },
              ],
              internalType: "struct Database.Digital",
              name: "digital",
              type: "tuple",
            },
          ],
          name: "recoverWallet",
          outputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
